### ISSUE TITLE
Invalid syntax after mutagenesis.

### ISSUE THREAD

**Issue by mariaangelesjs** [harryjubb/arpeggio#14]
Using:
`docker run --rm -v c:/<directory-location>:/<container-location> -u 1000:1000 -it arpeggio python /pathto/file.pdb -s RESNAME:xxx -v`
 
Output:

> File "/pathto/file.pdb", line 1
    ATOM      1  N   VAL B  19     -26.876 -10.933   2.860  1.00  0.00           N
              ^
SyntaxError: invalid syntax

**Comment by mariaangelesjs** [comment]
Hi Harry,
No worries, the issue was on the directory. I changed the location of the pdb file to a previous folder and it worked. I haven't checked the source code.
Kind regards,
Maria

**Comment by harryjubb** [comment]
Hi Maria,

In your example, `python` should come before `arpeggio.py`, `python` is throwing a `SyntaxError` because it's trying to run the PDB file as a script.

As long as the bind mount paths are correct, changing the location of the files shouldn't be a problem.

**Comment by mariaangelesjs** [comment]
Hi Harry,
I read the code afterwards and found that. Thanks.
Kind regards,
Maria
