### ISSUE TITLE
arpeggio translation to 3.7 - script works, but a few bugs

### ISSUE THREAD

**Issue by mariaangelesjs** [harryjubb/arpeggio#17]
Hi Harry,
I'm running arpeggio within the shell you provided after translating arpeggio to python 3.7. I was able to calculate contacts without using the `'-s'` command, but I  wasn't able to get the memory usage. This was the error I got: 

```
D:/arpeggio-master/arpeggio.py:110: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(x, collections.Iterable):
WARNING:root:Resource usage information not available ().
Running show contacts.
  File "D:/arpeggio-master/show_contacts.py", line 432
    print 'Please select XML-RPC (-xml) or script (-s) output.'
```
When I tried to calculate the interactions with a specific residue using` os.system('run_and_show.sh file.pdb -s /B/100/ -v') ` , this happened:
```
ERROR:root:Invalid selector: B:/100/
Traceback (most recent call last):
  File "D:/arpeggio-master/arpeggio.py", line 1408, in <module>
    selection = selection_parser(args.selection, entity)
  File "D:/arpeggio-master/arpeggio.py", line 239, in selection_parser
    raise SelectionError(original_selection)
__main__.SelectionError: B:/100/
Running show contacts.
  File "D:/arpeggio-master/show_contacts.py", line 432
    print 'Please select XML-RPC (-xml) or script (-s) output.'
```
Any ideas on how to solve this?

Note: I didn't change the lines related to those two errors.

**Comment by harryjubb** [comment]
Hi Maria, apologies for the long delay.

Great that you got it running in Python 3.7! I'd suggest taking a look at https://github.com/PDBeurope/arpeggio as PDBe have forked Arpeggio and made improvements, including translation to Python 3.
