### ISSUE TITLE
Default parameters on the webserver vs parameters command line

### ISSUE THREAD

**Issue by charlieccp** [harryjubb/arpeggio#20]
Hi,

I was wondering which parameters (from the list we can us in the command line) are used when the interactions are calculated on the webserver? i.e. if there is energy minimisation of the hydrogens, how many  hydrogen minimisation steps, with which forcefield (MMFF94,UFF or Ghemical), with which method (Distance Geometry, Steepest Descent or Conjugate Gradients), which compensation factor for VdW radii dependent interactions types, which distance cutoff for grid points to be 'interacting' with the entity and finally which pH is set as default?

Thank you

**Comment by harryjubb** [comment]
Hello,

I hope that https://github.com/harryjubb/arpeggio/issues/19 answers your questions, but please let me know if anything is missing.

All the best,

Harry

**Comment by charlieccp** [comment]
Oups sorry I did not see. Thanks a lot!
