### ISSUE TITLE
Multi chain protein complexes issue command line

### ISSUE THREAD

**Issue by charlieccp** [harryjubb/arpeggio#21]
Hi

I have got an error message while I was trying to find the interactions within a complexe made of 3 chains in the command line with the following parameters:
'[1KXV_1.clean.pdb', '-s', '/A/2/', '-s', '/A/154/', '-s', '/A/155/', '-s', '/A/203/', '-s', '/A/204/', '-s', '/A/205/', '-s', '/A/206/', '-s', '/A/208/', '-s', '/A/241/', '-s', '/A/243/', '-s', '/A/245/', '-s', '/A/246/', '-s', '/A/248/', '-s', '/A/249/', '-s', '/A/282/', '-s', '/A/283/', '-s', '/A/285/', '-s', '/A/288/', '-s', '/A/290/', '-s', '/A/291/', '-s', '/B/122/', '-s', '/B/123/', '-s', '/B/124/', '-s', '/B/133/', '-s', '/B/134/', '-s', '/B/138/', '-s', '/B/139/', '-wh', '-mh', '-ms', '10', '-mf', 'MMFF94', '-mm', 'ConjugateGradients', '-ph', '7.4', '-he']'
The error message was :
"This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information."
Only the .atomtypes is created.

However, while I tried to find the interactions in the same complexe at the same residues on the web server, the output files were solved quite fastly.

Is there a way to manage this kind of complexes with multiple chains in the command line? If not, please refer to my previous question which is: "What are the default parameters used on the webserver to find the interactions (number of hydrogen minimisation steps, forcefield, method ...) ?" so I can use the outputs from the webserver.

Thank you

**Comment by harryjubb** [comment]
> The error message was :
"This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information."

That error message is not generated by Arpeggio. As far as I can tell from a quick search, the message comes from Microsoft Visual C++/C# or similar runtimes.

Which method are you running Arpeggio with: using Docker, or installing locally? I have not tested Arpeggio in Docker on Windows, though I believe others have successfully. I have not at all tried to run Arpeggio natively on Windows at all, and wouldn't expect it to be straightforward for it to work that way.

Assuming the error is coming from something that is wrapping Arpeggio (Docker or Windows Python or other), unfortunately debugging that is outside of the scope of what I can help with.

Please see https://github.com/harryjubb/arpeggio/issues/21, referring to https://github.com/harryjubb/arpeggio/issues/19 for answers to your other questions.

All the best,

**Comment by charlieccp** [comment]
I am running Arpeggio with Anaconda in a Python 2.7 environment on Windows.

However, thanks for your answer!
