### ISSUE TITLE
Definition of the interactions

### ISSUE THREAD

**Issue by charlieccp** [harryjubb/arpeggio#22]
Hello,

I was wondering if you can link the definition you used for a weak hydrogen bond, hydrophobic interaction and so on. The hyperlinks linked to CREDO do not work.

Thank you.

Charlotte

**Comment by harryjubb** [comment]
Hi,

These are mostly defined in the Arpeggio Python code.

Atom typing criteria and contact types are detailed in [`config.py`](https://github.com/harryjubb/arpeggio/blob/master/config.py#L51-L669).

There are some [specific functions](https://github.com/harryjubb/arpeggio/blob/master/arpeggio.py#L427-L495) for [weak] hydrogen bond and halogen bond determination.

The full logic for interaction type assignment is in [`arpeggio.py`](https://github.com/harryjubb/arpeggio/blob/master/arpeggio.py#L1563-L1826).

See also notes on the interactions in the [README](https://github.com/harryjubb/arpeggio#contacts) and the [supplementary information](https://www.sciencedirect.com/science/article/pii/S0022283616305332) for the publication.

**Comment by harryjubb** [comment]
Closing unless there are further questions,
