### ISSUE TITLE
How to concentrate only on the interchain interactions

### ISSUE THREAD

**Issue by LDCS96** [harryjubb/arpeggio#24]
Hi, thanks for the software. 

I have a PDB for an antibody-antigen complex with three chains: H, L, N. However, the output of Arpeggio showed that it mainly concentrated on intrachain interactions like:

```
H/16/O	H/85/O	0	0	0	0	1	0	0	0	0	0	0	0	0	0	0	INTRA_SELECTION
N/119/O	N/140/O	0	0	0	0	1	0	0	0	0	0	0	0	0	0	0	INTRA_SELECTION

```
I want interchain interactions like:
```
H/x/x    N/x/x ...
L/x/x    H/x/x ...
```
How can I do that, on web server and in a programmatic way?

**Comment by harryjubb** [comment]
Hi @LDCS96,

Thanks for your interest.

I suspect there may be an issue with the selection of which entity to calculate contacts for. If there is no selection (or possibly an issue with the selection syntax), then Arpeggio will fall back to treating all atoms as selected, so all contacts are reported as `INTRA_SELECTION`.

The `.contacts` output file should still report all of the contacts in your structure, but they won't be filterable as `INTER` contacts without a valid selection. However, it should be possible to filter contacts to interchain contacts on the basis of having different chain identifiers in the first character of the first two tab-separated columns. If this is never the case in the output you got for your structure, that could be a bug, but I've not been able to reproduce this on the web server or command line. For example, for `10gs.pdb` with no selection:

```
A/98/OD2	B/64/NE2	0	0	1	0	0	1	0	0	0	0	0	0	0	1	0	INTRA_SELECTION
A/95/CA	B/64/NE2	0	0	0	0	1	0	0	0	0	0	0	0	0	0	0	INTRA_SELECTION
```

If you were only interested in interactions of antibody chains with the antigen, you could select the antigen with a command line option `-s /N//` (or in the selection textarea when uploading a structure to the web server: see the image below for syntax). On that run, all contacts between `N` and any other chain would be considered `INTER`, but interactions between `H` and `L` would not be calculated.

![image](https://user-images.githubusercontent.com/4588417/140188987-08dad7ce-9ce1-4550-8a95-78deec2f50e3.png)

If you specifically wanted all sets of inter-chain interactions between a single chain and the rest of the structure to be flagged as `INTER`, it would be a case of running three times with each chain selected. Depending on the size of your structure and selection it can be quicker to run with a selection than calculating all interatomic contacts without a selection.

If running programmatically, please could you share the command line options used to run Arpeggio, including any selections?

**Comment by harryjubb** [comment]
Closing this as answered, please reopen if any further questions.
