### ISSUE TITLE
arpeggio for RNA or DNA?

### ISSUE THREAD

**Issue by filipsPL** [harryjubb/arpeggio#25]
Can the arpeggio be used to detect interactions if the receptor is **RNA** or **DNA**? Tests indicate that it works for some cases, eg., for 1AJU, but fails to run on 1Q8N or 5SWE (RNA) and 3EM2 or 3MVB (DNA).

**Comment by harryjubb** [comment]
That shouldn't be a problem. If possible please can you share:

- The command used to run Arpeggio if using the command line; or otherwise the options given to the web server?
- Any error or warning messages you receive when running your failure cases

**Comment by n-szulc** [comment]
I am sharing links to web server calculations, in each case I used the default settings

- 1Q8N http://biosig.unimelb.edu.au/arpeggioweb/result/oranges-zebra-football/
- 5SWE http://biosig.unimelb.edu.au/arpeggioweb/result/william-neptune-november/
- 3EM2 http://biosig.unimelb.edu.au/arpeggioweb/result/hot-purple-oven/

**Comment by harryjubb** [comment]
Ah, I think Arpeggio is having an issue there with nucleotide-only structures. It's trying to build an internal representation of polypeptides, and failing where it can't find any.

I can look at updating the command line program but don't have guarantees on when I can be available to do this. I'd welcome any pull request with code changes to fix the issue.

Unfortunately the web server is unlikely to be updated from the original version distributed with the paper; I no longer have access to that version.

You could also try those structures with the PDBe's more active fork https://github.com/PDBeurope/arpeggio

**Comment by filipsPL** [comment]
Thank you for your prompt reply and clarification!
