### ISSUE TITLE
Running docker image : BioPython

### ISSUE THREAD

**Issue by pschmidtke** [harryjubb/arpeggio#9]
Hi Harry,

I wanted to run arpeggio using the docker image and the example you provide. I tried:  
`run --rm -v "$(pwd)":/run -u `id -u`:`id -g` -it harryjubb/arpeggio python arpeggio.py /run/1uyk.pdb -s RESNAME:PUX -v`

and i get : 
`INFO//11:52:21.248//Program begin.
INFO//11:52:21.321//Loaded PDB structure (BioPython)
INFO//11:52:21.701//Loaded PDB structure (OpenBabel)
ERROR//11:52:21.712//OpenBabel OBAtom with PDB serial number 1468 could not be matched to a BioPython counterpart.
Traceback (most recent call last):
  File "arpeggio.py", line 759, in <module>
    raise OBBioMatchError(serial)
__main__.OBBioMatchError
`

Any idea why this happens .... ? 

Cheers

Peter

**Comment by harryjubb** [comment]
Hi Peter,

That's usually an issue with alternate location atoms and/or duplicate atom serial numbers, unfortunately it was difficult to get OpenBabel to distinguish between different alternate locations for the same atom.

I'd recommend choosing choosing / removing alternate locations and seeing if that helps. The webserver does some basic tidying of PDB files to avoid some of the parsing errors.

See also https://github.com/harryjubb/arpeggio/issues/7, https://github.com/harryjubb/arpeggio/issues/8, https://github.com/harryjubb/arpeggio#frequently-asked-questions

Thanks for your interest in Arpeggio, let me know if I can help with anything :)

H

**Comment by pschmidtke** [comment]
ok that makes sense ... I'll try out your cleaning script then.


Thanks for the answer.


Peter


________________________________
